### ISSUE TITLE
При подключении db всплывает окно с ошибкой и не запускается

### ISSUE THREAD

**Issue by Muhamedzhan** [Muhamedzhan/OnlineShop#1]
![photo_2019-11-20 21 30 45](https://user-images.githubusercontent.com/33555639/69255772-96477000-0be2-11ea-8b3d-d3e28b0b972b.jpeg)
<img width="1538" alt="Снимок экрана 2019-11-20 в 22 11 09" src="https://user-images.githubusercontent.com/33555639/69255829-b1b27b00-0be2-11ea-8ebd-bbf437872e22.png">

У меня проблема с подключение db.
Все сделал, но всплывает окно (скриншот в приложении к сообщению) и не запускается. Не могу решить уже 2 дня.

Не могли бы подсказать, в чем может быть проблема?

@nightBaker

**Comment by nightBaker** [comment]
Проблема в этом классе
```csharp
public class Car
    {
        public int id { set; get; }
        [Key] <-----
        public string name { set; get; }
        public string shortDesc { set; get; }
        public string longDesc { set; get; }
        public string img { set; get; }
        public ushort price { set; get; }
        public bool isFavourite { set; get; }
        public bool available { set; get; }
        public int categoryId { set; get; }
        public virtual Category Category { set; get; }
    }
```

[Key] - должен быть над **id**
а вы поставили над **name**

так же в `Startup.cs`

вам нужно настроить route для начальной страницы, в вашем случае
```
 app.UseMvc(routes=>
            {
                routes.MapRoute(name: "default",
                    template: "{controller=Cars}/{action=List}/{id?}");
            }); 
```
